### ISSUE TITLE
Coinbase Slow rate limit exceeded

### ISSUE THREAD

**Issue by Stoner19** [jesse-ai/jesse#1]
When trying to pull candles from Coinbase it looks like it exceeds their rate limits. Candle settings that initially triggered the error were:

```
routes = [
    ('Coinbase', 'USDBTC', '15m', 'ExampleStrategy'),
]

extra_candles = [
    ('Coinbase', 'USDBTC', anchor_timeframe('4h')),
```
And my timeframe was just to the 1st of April, 2020. It populated about 65% of them and then gave me the rate limit error. 

ERROR:
```
============================== EXCEPTION TRACEBACK:
  File "/usr/local/bin/jesse", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jesse/__init__.py", line 250, in import_candles
    import_candles_mode.run(exchange, symbol, start_date)
  File "/usr/local/lib/python3.8/dist-packages/jesse/modes/import_candles_mode/__init__.py", line 74, in run
    candles = driver.fetch(symbol, temp_start_timestamp)
  File "/usr/local/lib/python3.8/dist-packages/jesse/modes/import_candles_mode/drivers/coinbase.py", line 52, in fetch
    self._handle_errors(response)
  File "/usr/local/lib/python3.8/dist-packages/jesse/modes/import_candles_mode/drivers/coinbase.py", line 83, in _handle_errors
    raise Exception(response.content)
=========================================================================

 Uncaught Exception: Exception: b'{"message":"Slow rate limit exceeded"}'
```

**Comment by saleh-mir** [comment]
Your routes have nothing to do with importing candles. They are just for backtests. 

That's odd. I have fetched years of data without hitting their limits. Maybe their servers were busy at the time or something. 

Either way, just run the `import-candles` command you just did minutes after, and it should start again and of course it'll skip duplicate candles so you will fast forward to where you were. 

I personally use Bitfinex for long history data, and Binance and newer dates. Their limits are better.

**Comment by Stoner19** [comment]
Ok thanks for the information. I did run `import-candles` again a few minutes after the import stopped and it did grab the rest of the candles without issues. May be worth just slowing down the call to import at coinbase so other users don't experience this too.

Also, if you are interested I'd love to join/start up a community chat platform. Discord seems to be the preferred program these days, but IRC is always a great option too :)

**Comment by saleh-mir** [comment]
Good idea. I will increase the sleep time for Coinbase. 

I have thought about the community. I'm going with a forum instead of realtime solutions for two reasons:
1. I want users' questions to be indexed by Google. So future users can find them. 
2. Realtime communities encourage the number of messages. Which means on average some send multiple messages per topic which is more time consuming for me. 

So for now I want Github issues to be the place users ask questions until I prepare a forum. Preparing a forum might be overkill but I have the experience of it. My other [open source project](https://github.com/voten-co/voten) was a social bookmarking platform with basically all the functionality a forum needs. So it should't take me this time (fingers crossed)

**Comment by Stoner19** [comment]
Thanks for making the sleep time changes to Coinbase. Forum sounds great, and I'll continue to use Github issues for the time being.
