### ISSUE TITLE
Uncaught Exception: ValueError: start_date must be a string representing a date before ...

### ISSUE THREAD

**Issue by yangboz** [jesse-ai/jesse#104]
after using jesse docker stack steps , after 'jesse import-candles Binance BTCUSDT 2019-11-17'  it throws:

```
Uncaught Exception: ValueError: start_date must be a string representing a date before today. ex: 2020-01-17
```

even I tried 'jesse import-candles Binance BTCUSDT 2019-11-17'

**Comment by saleh-mir** [comment]
Please ask such questions in the discord channel to receive help faster. The error says that `start_date` must be a string not the whole thing. So try this:
```
jesse import-candles 'Binance' 'BTCUSDT' '2019-11-17'
```

**Comment by saleh-mir** [comment]
Is it fixed?

**Comment by yangboz** [comment]
nope, still the same.

**Comment by jfreedman** [comment]
Seeing the same issue today when trying Jesse for the first time.  Followed instructions to create docker container and start postgres, when trying to import candles, it tells me "start_date must be a string representing a date before today" even though my start date is before today (and is valid):

jesse import-candles 'Binance' 'BTC-USDT' '2020-01-01'

**Comment by yangboz** [comment]
thanks @jfreedman ,but after upgrade arrow , throws error as follows:
 Uncaught Exception: SSLError: HTTPSConnectionPool(host='www.binance.com', port=443): Max retries exceeded with url: /api/v1/klines?interval=1m&symbol=BTCUSDT&startTime=1527811200000&endTime=1527871140000&limit=1000 (Caused by SSLError(SSLCertVerificationError("hostname 'www.binance.com' doesn't match either of '*.facebook.com', '*.facebook.net', '*.fbcdn.net', '*.fbsbx.com', '*.m.facebook.com', '*.messenger.com', '*.xx.fbcdn.net', '*.xy.fbcdn.net', '*.xz.fbcdn.net', 'facebook.com', 'messenger.com'"))), any idea?

**Comment by yangboz** [comment]
that's GFW's bad.
