### ISSUE TITLE
can't seem to use the --chart option

### ISSUE THREAD

**Issue by gfreches** [jesse-ai/jesse#105]
Everytime I run a backtest with the --chart option I run into this problem:
```
 File "/Applications/anaconda3/envs/crypto/lib/python3.8/site-packages/jesse/services/charts.py", line 84, in portfolio_vs_asset_returns
    price_dict[key]['prices'][price_dict[key]['indexes'][str(int(t.closed_at))]]
=========================================================================
 Uncaught Exception: KeyError: '1603929600000'
```
Using the csv output works fine and so does the json (I even used the graphical tool and it showed it fine)

**Comment by saleh-mir** [comment]
Which version of Jesse are you using? 

Run `jesse --version`

**Comment by Gabri** [comment]
I had similar problems too with charts in a previous version(s) but I tried now with version 0.18.2 and no more problems in my test

**Comment by saleh-mir** [comment]
Is this solved?

**Comment by noenfugler** [comment]
Got the same problem.
jesse, version 0.20.9

Found a confirmation on [Discord](https://discord.com/channels/771690508413829141/776363774185701396/807268433179574322).

Can confirm that seems to be linked to use of self.liquidate()

**Comment by noenfugler** [comment]
Seems to be related to line 85 of charts.py.  Suspect something to do with the last trade being open as the timestamp that is causing the key error is not in price_dict.

**Comment by saleh-mir** [comment]
I want to include the last trade in the chart too. Do you guys have a sample strategy that produces this error so I can reproduce the issue?

**Comment by noenfugler** [comment]
> I want to include the last trade in the chart too. Do you guys have a sample strategy that produces this error so I can reproduce the issue?

Great.  My fix never really got to the source of the issue, just caught it before it caused an exception.

It's odd though,  I'm having time reproducing the issue now.  I'll keep trying

**Comment by noenfugler** [comment]
Ok, got it.  Routes is:
```# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Make sure to read the docs about routes if you haven't already:
# https://docs.jesse.trade/docs/routes.html
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

from jesse.utils import anchor_timeframe

# trading routes
routes = [

    ('Binance Futures', 'BTC-USDT', '1h', 'HighPass'),
]

# in case your strategy requires extra candles, timeframes, ...
extra_candles = [
    ('Binance Futures', 'BTC-USDT', anchor_timeframe('1h')),
]
```
Check the files for strategy __init__ and Custom Indicator.  

Bactest parameters below.
$jesse backtest '2021-02-01' '2021-03-27' --chart

[__init__.py.zip](https://github.com/jesse-ai/jesse/files/6347237/__init__.py.zip)
[high_pass.py.zip](https://github.com/jesse-ai/jesse/files/6347239/high_pass.py.zip)
