### ISSUE TITLE
Symbols that don't have dash '-' in them

### ISSUE THREAD

**Issue by Darwinnn** [jesse-ai/jesse#163]
Hello,
Bitfinex symbols don't have a dash in them as a quote/base separator (see symbol list here: https://api-pub.bitfinex.com/v2/tickers?symbols=ALL)

And that creates a problem, since [`quote_asset()`](https://github.com/jesse-ai/jesse/blob/80f8797bc254d24b137fa84ca97807f6ed0f5c34/jesse/helpers.py#L520) is looking for a dash in symbol name and fails if there isn't one.

**Comment by cryptocoinserver** [comment]
Do you get an error? Just tested it and got no error? That's true about the Bitfinex symbol format, but that's all handled by Jesse behind the scenes.
We need the dash because otherwise, Jesse doesn't know which chars count to quote and which to base. Especially with those varying lengths (3 and 4 chars) these days.

**Comment by Darwinnn** [comment]
Yes, I do get an error:

```python
routes = [
    ('Bitfinex', 'ETHUSD', '2h', 'Test'),
]
```

```
root@4ea38a1669b7:/home/mybot# jesse backtest '2020-01-01' '2021-03-27'
============================== EXCEPTION TRACEBACK:
  ...
  File "/jesse-docker/jesse/helpers.py", line 504, in quote_asset
    raise InvalidRoutes("The symbol format is incorrect. Correct example: 'BTC-USDT'. Yours is '{}'".format(symbol))
=========================================================================

 Uncaught Exception: InvalidRoutes: The symbol format is incorrect. Correct example: 'BTC-USDT'. Yours is 'ETHUSD'
```

And for the dash:
```python
# trading routes
routes = [
    ('Bitfinex', 'ETH-USD', '2h', 'Test'),
]
```
```
============================== EXCEPTION TRACEBACK:
  ....
  File "/jesse-docker/jesse/services/required_candles.py", line 73, in load_required_candles
    raise CandleNotFoundInDatabase(
=========================================================================

 Uncaught Exception: CandleNotFoundInDatabase: No candle for Bitfinex ETH-USD is present in the database. Try importing candles.
 ```

Which makes sense, since what I have in the database is `ETHUSD` and not `ETH-USD`

```
jesse_db=# select distinct symbol from candle;
  symbol
----------
 ETHUSD
(1 row)
```

However, I just tried importing candles from Bitfinex specifically for `ETH-USD` and it loaded them correctly, but when I did this first time I clearly remember it saying something like `ETH-USD` is not found, but `ETHUSD` was found and that's what I imported.

Anyways, I think you just need to validate dash presence in symbols when doing a candle import, because it allows us to import dashless symbols which then won't work


```bash
root@4ea38a1669b7:/home/mybot# jesse import-candles 'Bitfinex' 'ETHUSD' '2018-01-01'
Importing 1182 days candles from "Bitfinex" for "ETHUSD". Duplicates will be skipped. All good? [Y/n]: Y
Importing candles...  [------------------------------------]    0%  00:40:54
```

**Comment by cryptocoinserver** [comment]
Good catch. Makes sense to validate that there already. I added it for the next release.
