### ISSUE TITLE
Tulips issue

### ISSUE THREAD

**Issue by laughingwithu** [jesse-ai/jesse#17]
After the update, strategies can't be backtested as the Tulipy module can't be found.

I manually installed Tulipy via pip but I am still getting same error.

**Comment by saleh-mir** [comment]
The update added Tulip as a dependency and the installation command now installs tulipy as well. Older installations have to do what you did but I'm not sure why you're still getting the error. 

Could you please leave me an example strategy and route for when you get the error?

**Comment by laughingwithu** [comment]
Worked it out. On Windows Tulipy requires Microsoft Visual C++ Build Tools to be installed

**Comment by saleh-mir** [comment]
Could you please send a PR for it on the docs repository?

Or leave it here so that I can addd it myself. Thank you

**Comment by firesurf** [comment]
hey :) thats why https://docs.jesse-ai.com/docs/getting-started/environment-setup.html#talib this step uses a pre built ta-lib. Normally the build tools would be needed too and they are big and take long to install. Maybe we can offer a prebuilt whl for tulipy too?

**Comment by firesurf** [comment]
https://pypi.org/project/tulipy/#files 
here they have prebuild whl

**Comment by saleh-mir** [comment]
@firesurf that would be great

**Comment by laughingwithu** [comment]
I agree the prebuilt whl would be the best approach.
