### ISSUE TITLE
Allow going short on spot type backtests

### ISSUE THREAD

**Issue by pdcribeiro** [jesse-ai/jesse#171]
**Is your feature request related to a problem? Please describe.**
Can't go short on spot type backtests

**Describe the solution you'd like**
If we have access to the current assets we can use them to filter out orders that we can't afford and avoid InsufficientMargin errors

**Describe alternatives you've considered**
We could keep track of that manually on the strategy but I think it makes more sense to just pass it down from the SpotExchange model

**Additional context**
Does this make sense or am I missing something here?

**Comment by pdcribeiro** [comment]
I just found out we can get them through `self.position.exchange.available_assets`. Maybe we could have an attribute for that directly in Strategy?

**Comment by pdcribeiro** [comment]
And add it to the docs either way

**Comment by saleh-mir** [comment]
Hi there. Do you mean that if we're starting with a capital more than 0 for an asset (like BTC), then it makes sense to be able to `go_short` on it?

**Comment by pdcribeiro** [comment]
I was thinking that even if you started with 0 BTC, you would eventually increase your balance with long orders and then could use that balance to open short orders. But maybe that doesn't make sense. I'm still new to the game :b

However, the scenario you mentioned sounds like a good use case for this

**Comment by saleh-mir** [comment]
@pdcribeiro are on on the Discord server?

**Comment by pdcribeiro** [comment]
I am now :)

**Comment by saleh-mir** [comment]
Hey. I removed the spot support in the upcoming dashboard and will bring it fully back after the official release. Thank you
