### ISSUE TITLE
Allow import-candles outside of a Jesse project

### ISSUE THREAD

**Issue by pdcribeiro** [jesse-ai/jesse#172]
**Is your feature request related to a problem? Please describe.**
Can't run `jesse import-candles ...` outside of a Jesse project

**Additional context**
Unless I'm missing something, candle importing is not associated with any project and shouldn't require the user to be in a specific folder

**Comment by saleh-mir** [comment]
It still needs to read from the `config.py` file to know about the database credentials.

**Comment by pdcribeiro** [comment]
You're right, my bad :sweat_smile:
