### ISSUE TITLE
Received spam mail

### ISSUE THREAD

**Issue by smeijer** [jesse-ai/jesse#176]
> IMPORTANT: Please open an issue ONLY if you find something wrong with the source code. 

**Describe the bug**
> A clear and concise description of what the bug is. Include the whole error message / traceback.

I've received a spam mail from you guys. 

**To Reproduce**
> Steps to reproduce the behavior:

1. Open my email 
2. There it was

**Expected behavior**
> A clear and concise description of what you expected to happen.

I did not expect to receive spam. 

**Screenshots**
> If applicable, add screenshots to help explain your problem.

![Screenshot_20210416-201245](https://user-images.githubusercontent.com/1196524/115067260-ef5b2680-9ef0-11eb-91a2-69e929ebbb6c.jpg)

**Environment (please complete the following information):**
 - OS: Android
 - Version: Jesse not found

**Additional context**
> Add any other context about the problem here.

Sending spam mails is unethical.

**Comment by saleh-mir** [comment]
The content of that email does not seem spam to me. I'm sorry if you feel that way and you won't receive. a mail from us again. 

However, creating an issue and labeling it as bug is spamming the repository.

**Comment by hnspn** [comment]
> Sending spam mails is unethical.
got a link to that github repo where we figured out objective morallity?
writing closed source software is unethiccal according to some

**Comment by weyert** [comment]
I am glad to know you don't mind me getting your email address form Github and mail you about finance product I am offering.

**Comment by saleh-mir** [comment]
@weyert I don't mind getting p2p friendly emails. Otherwise, I wouldn't have set my email open in my public profile.
