### ISSUE TITLE
AttributeError: module 'routes' has no attribute 'routes'

### ISSUE THREAD

**Issue by leverageinventions** [jesse-ai/jesse#19]
I am using Linux. Used the script to install everything from a fresh installation. Configured and ran the psql service and db. No luck running Jesse. Stuck on import-candles. Following is the error:

jesse import-candles Bitfinex BTCUSD 2019-01-01

Traceback (most recent call last):
  File "/usr/local/bin/jesse", line 5, in <module>
    from jesse.__init__ import cli
  File "/usr/local/lib/python3.8/dist-packages/jesse/__init__.py", line 60, in <module>
    inject_local_routes()
  File "/usr/local/lib/python3.8/dist-packages/jesse/__init__.py", line 53, in inject_local_routes
    router.set_routes(local_router.routes)
AttributeError: module 'routes' has no attribute 'routes'

**Comment by firesurf** [comment]
Did you create the project? https://docs.jesse-ai.com/docs/getting-started/#create-a-new-project

**Comment by saleh-mir** [comment]
Please ask such questions in the forum:
http://forum.jesse-ai.com

Leave the result of `cat routes.py` so I can take a look.

**Comment by leverageinventions** [comment]
> Did you create the project? https://docs.jesse-ai.com/docs/getting-started/#create-a-new-project

Yes, I created the project AND run the commands inside the project folder, otherwise the command throws an error saying to do so.

**Comment by leverageinventions** [comment]
> Please ask such questions in the forum:
> http://forum.jesse-ai.com
> 
> Leave the result of `cat routes.py` so I can take a look.

Yes,  here is the result. Basically it is the auto generated one, I just changed Binance to Bitfinex and the timeframe, but I also tried running it without changing anything on it and it throws the same error.

cat routes.py

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Make sure to read the docs about routes if you haven't already:
# https://docs.jesse-ai.com/docs/routes.html
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

from jesse.utils import anchor_timeframe

# trading routes
routes = [
    ('Bitfinex', 'BTCUSD', '1h', 'ExampleStrategy'),
]

# in case your strategy requires extra candles, timeframes, ...
extra_candles = [
    ('Bitfinex', 'BTCUSD', anchor_timeframe('1h')),

**Comment by leverageinventions** [comment]
> I am using Linux. Used the script to install everything from a fresh installation. Configured and ran the psql service and db. No luck running Jesse. Stuck on import-candles. Following is the error:
> 
> jesse import-candles Bitfinex BTCUSD 2019-01-01
> 
> Traceback (most recent call last):
> File "/usr/local/bin/jesse", line 5, in 
> from jesse.**init** import cli
> File "/usr/local/lib/python3.8/dist-packages/jesse/**init**.py", line 60, in 
> inject_local_routes()
> File "/usr/local/lib/python3.8/dist-packages/jesse/**init**.py", line 53, in inject_local_routes
> router.set_routes(local_router.routes)
> AttributeError: module 'routes' has no attribute 'routes'

I just added a print(local_router) just before the line 53 that throws the error, here is the result:

<module 'routes' from '/usr/lib/python3/dist-packages/routes/__init__.py'>

Shouldn't the path be the routes.py inside the project folder (which is in other location, and does have the trading routes variable defined?

**Comment by leverageinventions** [comment]
It is weird because the locate('config.config') in line 41 reads the config.py in the project directory instead of the config.py in the jesse package directory, but in contrast the locate('routes') in line 50 reads the routes/__init__.py in the jesse package directory instead of the routes.py in the project directory.

It looks like this is causing the problem.

**Comment by saleh-mir** [comment]
Did you merely ran the installer script in a fresh ubuntu 18.04 or did you do anything else? Because I just did a fresh installation with the script yesterday and everything was fine. The error you're reporting is really weird, as if you don't have `Jesse` installed with `pip`. 

Is there any chance you could give me access to your VPS to see it for myself?

**Comment by leverageinventions** [comment]
> Did you merely ran the installer script in a fresh ubuntu 18.04 or did you do anything else? Because I just did a fresh installation with the script yesterday and everything was fine. The error you're reporting is really weird, as if you don't have `Jesse` installed with `pip`.
> 
> Is there any chance you could give me access to your VPS to see it for myself?
> 
> p.s: please use "```" before and after of posted outputs for a better formatting. What you do makes it hard to read.

Yes, I merely ran the installer script but I am using a fresh image of latest Kali Linux instead of Ubuntu. It updated/installed everything without problems.

jesse appears in ```pip list```, it is version 0.4.2

I am not using a VPS, I am running it in a VM on my computer dedicated just for Jesse.

**Comment by leverageinventions** [comment]
If it helps I can install teamviewer on the VM so you can take a look.

Or let me know if there is any other info you need.

**Comment by leverageinventions** [comment]
I managed to solve the issue. The problem is in line 17: ```sys.path.append(os.getcwd())```

By appending to sys.path it adds the working directory to the end of the list. So when the ```locate()``` function is searching for the classes it finds the ```routes``` in the jesse package directory first, which doesn't have the attributes needed.

I changed that line to: ```sys.path.insert(0, os.getcwd())```

So now the CWD is the first directory the program looks at and finds the correct routes.

What is weird is that nobody else seems to have the problem considering that locate() looks at the path list in order.

Anyway, I just ran my first sample backtest and all good.

I hope you can add this change in a future release.

Thanks for the support and for sharing this amazing project!

**Comment by saleh-mir** [comment]
It was a weird bug because as you said why is it working on other operating systems?! 
Anyways, thank you for the issue and for the fix. I updated and pushed version `0.5.0` with it. You can update and it should work. I thanked you in the forum too:
https://forum.jesse-ai.com/d/49-version-050-is-released
