### ISSUE TITLE
optimize propages DNA with "None" results

### ISSUE THREAD

**Issue by themantalope** [jesse-ai/jesse#191]
**Is your feature request related to a problem? Please describe.**

When running optimize mode, the program will propagate DNA that results in "None" for the various optimization metrics.

**Describe the solution you'd like**

DNA resulting in "None" results should be eliminated from the population.

**Describe alternatives you've considered**

You could leave them in there, as some parameters may be useful, but it's perhaps one or two that's causing a problem, but their fitness score should be significantly decreased so they don't make up a large percentage of the population.

**Additional context**
![cropped_dna](https://user-images.githubusercontent.com/7599879/118398361-d5ab1d00-b61d-11eb-91d1-9d3aa770df2e.png)

**Comment by cryptocoinserver** [comment]
Thank you. The fitness score is already set to a very low number (score = 0.0001) in those cases.
