### ISSUE TITLE
[Q] Backtesting and Optimization

### ISSUE THREAD

**Issue by d3xterCon** [jesse-ai/jesse#2]
Just a short question. Will the framework use CPU or GPU for backtesting and optimization?

**Comment by saleh-mir** [comment]
CPU only. For backtests it uses a single core. For optimize mode (which isn't released yet) it uses as many CPU cores as you have to do parallel training.

**Comment by d3xterCon** [comment]
> CPU only. For backtests it uses a single core. For optimize mode (which isn't released yet) it uses as many CPU cores as you have to perform parallel training.

So parallel processing in a pi cluster would also work?

**Comment by saleh-mir** [comment]
I'm not familiar with PI cluster. Jesse uses Python's built-in multiprocessing module:
https://docs.python.org/3/library/multiprocessing.html

**Comment by d3xterCon** [comment]
Thanks for the information. Will have a look at it.
