### ISSUE TITLE
First backtestable timestamp calculated from wrong timeframe

### ISSUE THREAD

**Issue by farukuzun** [jesse-ai/jesse#212]
**Describe the bug**
While loading the initial candles, jesse uses biggest timeframe in the routes file as a reference to calculate first available date for that route.

**Expected behavior**
It should use timeframes from routes file.

**Comment by saleh-mir** [comment]
Hey, Thank you for this. Because of the way candle injection (loop) works in the backtest, requires candles to have the same length

**Comment by farukuzun** [comment]
With this fix, it'll still raise `CandleNotFoundInDatabase` if one of the routes doesn't have enough candles backwards from `backtest_start_date` to `backtest_start_date - env.data.warmup_candles_num  * timeframe`. And they'll be same length.
