### ISSUE TITLE
Wrong result provided by Kaufmanstop in long direction

### ISSUE THREAD

**Issue by nicolaspapp** [jesse-ai/jesse#227]
**Describe the bug**
There is a problem in the following line: https://github.com/jesse-ai/jesse/blob/master/jesse/indicators/kaufmanstop.py#L30
Long direction is returning negative values as an answer. I believe the correct calculation would be:

```
res = low - (hl_diff * mult)  if direction == "long" else hl_diff * mult + high
```

instead of 

```
res = hl_diff * mult - low if direction == "long" else hl_diff * mult + high
```

**Comment by cryptocoinserver** [comment]
Did a short search and it seems you are right.
_"In Kaufman's technique, compute the average daily high-low price range for the prior month, multiply by 2, and then subtract the result from the current low price."_
[http://thepatternsite.com/stops.html](http://thepatternsite.com/stops.html)
I will fix it.
