### ISSUE TITLE
Optimization mode fails with more than 100 cpu cores

### ISSUE THREAD

**Issue by farukuzun** [jesse-ai/jesse#235]
Tried to optimize a strategy with Ryzen 3990X, it failed at %1 with ` Uncaught Exception: ZeroDivisionError: integer division or modulo by zero`. 

On `jesse/modes/optimize_mode/Genetics.py` line 360 is the problem.
```python
360:                     if i != 0 and i % int(100 / self.cpu_cores) == 0:
361:                        self.take_snapshot(i * self.cpu_cores)
```
`int(100/128) = 0` in my case.

**Comment by saleh-mir** [comment]
Thanks for reporting. I didn't know such CPU exists!

**Comment by saleh-mir** [comment]
That line is commented in the version `+0.30.0`. It should work now
