### ISSUE TITLE
proxy problem ，How to set proxy

### ISSUE THREAD

**Issue by yuzhupeng** [jesse-ai/jesse#240]
![image](https://user-images.githubusercontent.com/17597006/132829081-f918465d-ac7b-42a1-9d4b-c315b62be220.png)

**Comment by saleh-mir** [comment]
It seems that your IP has reached its limit for Binance's API. Is that because you were importing in a few sessions at the same time?

**Comment by saleh-mir** [comment]
Sorry for the late reply, I usually check Discord
