### ISSUE TITLE
Dashboard : Equity Curve chart showing invalid dates and time

### ISSUE THREAD

**Issue by Gabri** [jesse-ai/jesse#242]
Hello,

Latest version of branch dashboard.
When you move the mouse over the Equity curve graph it shows "strange" dates, everyone at 08:00 as hour:
![image](https://user-images.githubusercontent.com/154831/134071236-31144103-1fe9-4e47-a56d-db3a459f1f6d.png)

Also other time data on Results page are "invalid", they seems timestamps or intervals in seconds maybe;
![image](https://user-images.githubusercontent.com/154831/134125983-277a2833-70a8-4fb2-87cd-48ede7377d62.png)

Anyway, probably you already know about them

Hope it helps

**Comment by saleh-mir** [comment]
Thanks Gabriel. I will fix it for the coming release. 

> Also other time data on Results page are "invalid", they seems timestamps or intervals in seconds maybe;

They were in seconds. I have converted them into a human-readable format in the new release. 

Thanks again

**Comment by saleh-mir** [comment]
This is now solved in the RC version. Thanks again man
