### ISSUE TITLE
Using Jesse as a screener

### ISSUE THREAD

**Issue by Antonhansel** [jesse-ai/jesse#264]
Hello,

I would like to know if there are examples of jesse being used as a crypto screener rather than a crypto trading bot, sending notifications with relevant informations over a telegram channel for example,

Anton

**Comment by saleh-mir** [comment]
Hey Anton

You can get answers to such questions on our Discord faster. 

That's easy. Just define as many routes as you need, and make sure `should_long` and `should_short` are both returning `False`. In such a case, the strategy won't make trades, but it will still get executed on every new candle giving you the chance to do your screening and get notifications for important events. You can use the `self.log()` method for quickly sending notifications (Jesse supports Telegram and Discord drivers at the moment)
