### ISSUE TITLE
Using Julia

### ISSUE THREAD

**Issue by c0indev3l** [jesse-ai/jesse#276]
Hello,

have you ever considered using Julia instead of Python ?
https://julialang.org/benchmarks/

Kind regards

**Comment by cryptocoinserver** [comment]
Julia is a great language, but Python is way more popular and has many more libraries / projects. So more people already can code in Python, and we can take advantage of many great Python libraries.
It's true that Python is slower here and there, but that can be solved using Cython or JIT Compilers for that code parts.

Thank you for your advice, though!
