### ISSUE TITLE
Not enough candles for Binance BTC-USDT exists to run backtest

### ISSUE THREAD

**Issue by mikeejazmines** [jesse-ai/jesse#282]
**Describe the bug**
I followed the tutorial, went through pulling candles and storing them into the database. Tried to run backtest but am getting an error of

` Uncaught Exception: CandleNotFoundInDatabase: Not enough candles for Binance BTC-USDT exists to run backtest from 2020-07-01 => 2021-10-01. `
`First available date is 2018-07-12`
`Last available date is 2021-12-03`

**To Reproduce**
1. Create a new project
2. run `jesse import-candles 'Binance' 'BTC-USDT' '2020-06-01'`
3. run `jesse backtest '2020-07-01' '2021-10-01'` to backtest

Then error occurs

**Screenshots**

<img width="484" alt="Screen Shot 2021-12-03 at 11 20 54 AM" src="https://user-images.githubusercontent.com/12680278/144539518-af532d95-3890-4f39-950e-7d6837f5c252.png">

**Enviroment (please complete the following information):**
MAC OS
Name: jesse
Version: 0.29.3

**Comment by baniol** [comment]
with `extra_candles = []` in routes.py the initial example works

**Comment by saleh-mir** [comment]
Hi. This is often because of the need for warmup candles:
https://jesse.trade/help/faq/i-imported-candles-but-keep-getting-not-enough-candles

Soon I intend to modify this behavior to NOT preload warmup candles to prevent the confusions.
