### ISSUE TITLE
Dynamic Leverage

### ISSUE THREAD

**Issue by pantuchy** [jesse-ai/jesse#285]
Hello.

Is is possible to add possibility to update leverage before every new trade with helper functions or with self.leverage. 
For example on another tick (candle) my strategy allows to open LONG position with open price = 500, stop price = 450, balance 1000, risk 1% from balance and leverage for that trade will be = 5. In that case total position notional will be 100, size (quantity) = 0.2 and my margin for that order = 20 (because of leverage = 5). And now until position is opened I will not change leverage, only add more margin. But when position will be closed and after some time strategy decide to make new trade, before opening new position I should be able to change leverage for example to 7 (previous was = 5) and etc.

Is it possible?

Thank you.

**Comment by cryptocoinserver** [comment]
Currently, it's not possible and would require many changes in both the main framework and live plugin. I added it to the ideas on our roadmap though:
https://trello.com/c/wuuH2JUX/33-dynamic-leverage

Thank you for your suggestion.
