### ISSUE TITLE
EMA indicator gives wrong outcome in debug in comparing with Tradingview and Binance

### ISSUE THREAD

**Issue by BoringBravo21** [jesse-ai/jesse#298]
He guys,

someone pointed out to me that the EMA from the backtest does not display the value as in tradingview.

Now I have delved deeper into the problem and found out that the EMA is indeed wrong.

Looking at the EMA values ​​from my debug of my script and the value of tradingview (see Binance) in a CSV file, it can be concluded that there seems to be an error in the calculation of the EMA.

Now the values ​​I get from my backtest are equal to the values ​​of the MA in tradingview and Binance.

Now I have put both python scripts side by side and I have to conclude that there is no difference in both scripts. It is also the case that there seems to be no difference, especially in the calculation strings. This insinuates to me that there is quite a mistake in the calculation of the EMA.

What do you think about this?

With kind regards,

Jhon

**Comment by cryptocoinserver** [comment]
Hello Jhon,

> Now I have put both python scripts side by side and I have to conclude that there is no difference in both scripts.

That might look to you like that, but it's not the same. Both wrap the most well known indicator library in python / c++:
`res = talib.SMA(source, timeperiod=period)`
vs.
`res = talib.EMA(source, timeperiod=period)`

To be honest, I think it's pretty unlikely that talib did something wrong. 
Probably more related to the memory of indicators:
[https://jesse.trade/help/faq/i-changed-the-warm-up-candles-config-why-do-my-indicator-values-change](https://jesse.trade/help/faq/i-changed-the-warm-up-candles-config-why-do-my-indicator-values-change)
The example graphic even uses the EMA.

You can try increasing the warm_up_candles to a very big number. 

Have a great day
Markus

**Comment by Audiotuete** [comment]
Thanks a lot, this solved the problem. When calculating the EMA with a period of 200 you have to preload at least 270 candles, otherwise the output is wrong. As a rule of thumb I would suggest "period + 100" preloaded candles.  I think it would be helpful to add a hint to the documentation for long period indicators.

**Comment by cryptocoinserver** [comment]
Good. Will add that hint.
