### ISSUE TITLE
GUI wrong behaviour?

### ISSUE THREAD

**Issue by jstam84** [jesse-ai/jesse#299]
**Describe the bug**
Since I don't know if it's by design, I'm posting this as a bug. Jesse Live Trading from the GUI is 'lost' when closing the browser. On opening the UI in a seperate tab, the current live trading isn't visible anymore. Is this normal behaviour? It seems to me that when live trading is running (or is it canceled upon close?), it should always be visible when reopening the UI.

**Comment by saleh-mir** [comment]
One issue that I am aware of is that if you open a second browser tab, it'll mess with things. For which I intend to implement a warning pop-up or something. 

But if you start a live trade, close the browser tab, and then open the http://localhost:8080/#/live/1 address again, it should bring back the same trading session just fine. Are you saying that in your case this is the case but not working?
