### ISSUE TITLE
In "import candles"panel, symbol field does not allow more than 9 chars

### ISSUE THREAD

**Issue by csand83** [jesse-ai/jesse#310]
**Describe the bug**
When starting an import of candles, the field symbol can not contain more than 9 chars so you can not download data for crypto pairs like MATIC-USDT or PEOPLE-USDT ...

**To Reproduce**
Got to the import candles panel (UI) and try to put PEOPLE-USDT in the field symbol.
**Expected behavior**
Field length should be extended
**Screenshots**
N/A
**Enviroment (please complete the following information):**
 - OS: Ubuntu
 - Version 0.32.1

**Additional context**
None

**Comment by saleh-mir** [comment]
Thank you for reporting. Will push a fix soon

**Comment by saleh-mir** [comment]
Just pushed version `0.32.2` that fixes this. Thanks again
