### ISSUE TITLE
new testing on raspberry now with docker.

### ISSUE THREAD

**Issue by anakein** [jesse-ai/jesse#338]
run all but don´t work.

Tbot@bottrading:~/tbot_jesse/docker $ docker-compose up -d
Starting postgres ... done
Starting redis    ... done
Starting jesse    ... done
Tbot@bottrading:~/tbot_jesse/docker $ docker-compose logs
Attaching to jesse, postgres, redis
jesse       | standard_init_linux.go:228: exec user process caused: exec format error
jesse       | standard_init_linux.go:228: exec user process caused: exec format error
jesse       | standard_init_linux.go:228: exec user process caused: exec format error

**Comment by saleh-mir** [comment]
Raspberry Pi is not officially supported. But I'm guessing you should look this up as a docker issue rather than Jesse issue. Also, I suggest running the `docker-compose` command without the `-d` flag so you can see the output logs.

**Comment by royshil** [comment]
i'm getting the same on RasPi (actually NanoPi M4 running dietpi v8.4)
resorted to using the non-docker version

**Comment by saleh-mir** [comment]
@royshil can you please let me know the **extra** steps you took to install it? I have a RP4 myself, once I find the time I'd like to try it and add support for it.
