### ISSUE TITLE
Add ability to change hyperparameters on backtest

### ISSUE THREAD

**Issue by royshil** [jesse-ai/jesse#341]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when backtesting my strategy and keep having to change code in order to test different hyperparameter values, which are already defined except there's no way to change them.

**Describe the solution you'd like**
I'd like a UI in the backtest page that allows to change the hyperparamters values.

**Describe alternatives you've considered**
Creating multiple Strategies, e.g. different Python classes, with different parameter values.

**Comment by saleh-mir** [comment]
Do you have like a list of DNA strings that you want to backtest?

**Comment by domett93** [comment]
For me it would also be great if I could modify the hyperparameters in the backtest page without changing my code.

It would be nice if there is some kind of text box for each hyperparameter in my strategy that i can adjust and use for backtest.

When I want to do that I don't have any DNA strings

**Comment by saleh-mir** [comment]
@domett93 great suggestion. I will remember it in the future.
