### ISSUE TITLE
Investement 

### ISSUE THREAD

**Issue by ILYESBEJIA** [jesse-ai/jesse#345]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Hi man i'm interest to invest in your project to promote my company is there any demo online of your trading bot ??

**Comment by saleh-mir** [comment]
This question is not suitable as a Github issue. This video on our Youtube channel is a good place for a preview:
https://www.youtube.com/watch?v=nlV8Y0QeWfc

If you're interested in sponsoring the project in exchange for banners on the documentation website for example, please contact me at `sponsor@jesse.trade`.
