### ISSUE TITLE
utils.crossed always return ValueError: The truth value of an array with ..

### ISSUE THREAD

**Issue by eyussf** [jesse-ai/jesse#346]
the utils.crossed function always return ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

`        return utils.crossed(self.sma1, self.sma2, 'below')
`

sma1,sma2

`  @propert`  y
`      def sm1(self):`  
   `       return ta.sma(self.candles, 100, sequential=True)`

` @property`  
    `  def sm2(self):`  
     `     return ta.sma(self.candles, 50, sequential=True)`

**Comment by cryptocoinserver** [comment]
[https://jesse.trade/help/faq/i-got-valueerror-the-truth-value-of-an-array-with-more-than-one-element-is-ambiguous-use-aany-or-aall](https://jesse.trade/help/faq/i-got-valueerror-the-truth-value-of-an-array-with-more-than-one-element-is-ambiguous-use-aany-or-aall)

It's not a bug. You need to pass a series. Currently, you pass the whole candle array. 
Passing this will work: `candles_close = candles[:, 2]`

**Comment by cryptocoinserver** [comment]
If you are certain it's a bug please share the whole error massage / traceback, so we can see the origin.
