### ISSUE TITLE
go_long and go_short at the same time because of a hedge fund strategy

### ISSUE THREAD

**Issue by SavvyEngineer** [jesse-ai/jesse#348]
Hi there,
based on your document I know that it's not possible to return true out of both go_long and go_short at the same time but because of our strategy I need the set of orders one buy and one sell with the same lot size at the same time and the same price is there any other approach? 
I found this 
https://github.com/jesse-ai/jesse/blob/master/jesse/strategies/TestHasLongAndShortEntryOrdersPropertiesInFilters/__init__.py
 but it doesn't solve my problem any help will be highly appreciated

**Comment by saleh-mir** [comment]
Submitting both buy and sell orders for entering trades is not currently supported based on our design. Maybe you can use the `before()` and `self.vars()` to cook something custom for making the decision of whether going long or short and then later doing it. 

Please use the Discord server for asking such questions so we can help you faster. I see the Github issues for bug reports directly related to the code.
