### ISSUE TITLE
Equal weight capital UI checkbox

### ISSUE THREAD

**Issue by theretohere** [jesse-ai/jesse#349]
Can there be a checkbox in the UI, for something like "equal weight capital"? 

Or more advanced, a set of text boxes that appear if you select "distribute capital" that require the numbers to add to 100%?

This would save users from having to code this every time:

https://jesse.trade/help/faq/i-keep-getting-insufficentmargin
"Do you have multiple routes? Then you need to make sure that each route only uses a fraction of your capital / available margin. An example would be: self.capital / fraction_to_use - fraction_to_use should equal the weight you want to assign the route. The sum of all fraction_to_use mustn't exceed 1. To assign the same amount to all routes you can set fraction_to_use to the number of routes."

**Comment by saleh-mir** [comment]
I'm adding this to our future to-do list. I very much like this idea and even tried to implement it once. But there were details I couldn't work out at the time. I'll tackle it in the future.
