### ISSUE TITLE
Binance API key errors fails silently

### ISSUE THREAD

**Issue by shhhmel** [jesse-ai/jesse#365]
**Describe the bug**
I had such error **jesse.exceptions.InvalidExchangeApiKeys: [401 ERROR]: Your API keys for Binance Perpetual Futures are either wrong or don't have the correct permissions**
I have Telegram notifications enabled, other Notifications worked well but this error was not show in Telegram at all.
So I had to go to logs and find it mannulay.

**To Reproduce**
1. Create API keys for Binance Perpetual Futures with turned off Futures access.
2. This error will be after Jesse will try to make a deal.

**Expected behavior**
Error should be send to the Telegram.

**Enviroment (please complete the following information):**
 - OS: Ubuntu
 - Jeese:  0.39.3
 - Live server: 0.39.0

**Comment by saleh-mir** [comment]
I tried this and I get the error right after starting the session (and not just when it wants to submit an order) which is why I don't see why a telegram notification is required.
