### ISSUE TITLE
outdated websockets lib 

### ISSUE THREAD

**Issue by movy** [jesse-ai/jesse#369]
**Describe the bug**
I installed jesse w/o docker and upon running frontend I see the following error:

`TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary`

Quick googling showed it's related to websockets, and updating them to latest version (10.3) resolved the problem for now: frontend works and I'm fetching candle data now. Will see if the updated version causes any problems down the line, but maybe worth updating `requirements.txt`

https://github.com/jesse-ai/jesse/blob/3cf49413f5919123b2097bd3f2d797a345d8eb94/requirements.txt#L28

On the same note, there's no `numba==0.53` available on Ubuntu 22.04 (`ERROR: No matching distribution found for numba==0.53`), so I just installed the latest one. IF version number is not critical, maybe can update the docs also. 

**Enviroment (please complete the following information):**
 - OS: Ubuntu 22.04, no Docker.

 - Version: 0.39.5

**Comment by saleh-mir** [comment]
Hi there

Did you install it via our docker guide?
https://docs.jesse.trade/docs/getting-started/docker.html

As for Numba, one of its dependancies didn't play nice with one of our main dependancies (I think it was numpy). So I'm not sure it'll work for you that way. Lemme know how it goes. 

Thank you

**Comment by movy** [comment]
Saleh, 
As I mentioned, I'm not using Docker as Jesse is pretty easy to set up manually and in such scenarios I consider Docker as unnecessary middle man. Everything works fine after I updated websockets lib to 10.3, so it might be a good idea to make this version default (but I haven't tried live trading yet, I just assume websockets are in use there too?)

**Comment by saleh-mir** [comment]
I'm closing this until we get more info. Thank you for repoting
