### ISSUE TITLE
Precision Bug

### ISSUE THREAD

**Issue by ynzheng** [jesse-ai/jesse#374]
I found somthing wrong in "Binance PERPETUAL Futures" trading with jesse,
so I log the price and qty Precision in before() as following:
```
    def before(self):
        if self.index == 0 and self.symbol == 'BTC-USDT':
            self.log("_price_precision=" + str(self._price_precision)) 
```

I got the log as :
```
[INFO | 2022-09-27T04:20:00] _price_precision=1
```
but infact , in  `https://fapi.binance.com/fapi/v1/exchangeInfo`
the "BTCUSDT" symbol **PERPETUAL SHOULD BE** `_price_precision=2`,
So I think maybe you take the QUARTER pricePrecision as the PERPETUAL ...
```
    {
      "symbol": "BTCUSDT",
      "pair": "BTCUSDT",
      "contractType": "PERPETUAL",
      "pricePrecision": 2,
    }
    
    {
      "symbol": "BTCUSDT_220930",
      "pair": "BTCUSDT",
      "contractType": "CURRENT_QUARTER",
      "pricePrecision": 1,
    }
    {
      "symbol": "BTCUSDT_221230",
      "pair": "BTCUSDT",
      "contractType": "NEXT_QUARTER",
      "pricePrecision": 1,
    }   
```

at last,  in `https://github.com/jesse-ai/jesse/blob/master/jesse/helpers.py#L104`

it will be better add following ,FYI:
```
def dashy_symbol(symbol: str) -> str:

......

    #add
    if symbol[-4:] in ["USDT","BUSD","DOGE","USDP","BIDR","IDRT","TUSD","USDC"] :
        return f"{symbol[0:-4]}-{symbol[-4:]}"
    elif symbol[-3:] in ["BTC","ETH","BNB","XRP","TRX","DOT","AUD","BRL","EUR","GBP","RUB","TRY","DAI","UAH","VAI","NGN"] :
        return f"{symbol[0:-3]}-{symbol[-3:]}"
    #add end

    return f"{symbol[0:3]}-{symbol[3:]}"
```

**Comment by saleh-mir** [comment]
That is how I did it at first too. But later we had errors related to price precision. After digging I found out that the `pricePrecision` is not the correct precision that Binance expects. Instead the `tickSize` from the `filters` section of that endpoint is. We had no errors after that. Here's my code:

```py
'price_precision': int(
    abs(math.log10(float(si['filters'][0]['tickSize'])))
),
'qty_precision': int(si['quantityPrecision']),
```

**Comment by ynzheng** [comment]
can you check if jesse take the QUARTER "pricePrecision" as the PERPETUAL ...?

what I mean is, 

maybe, there will be an error, even it use tickSize to caculate price_precision 

If jesse use the `"pair": "BTCUSDT"`, not the `"symbol": "BTCUSDT"` (data from binance `exchangeInfo`) as the BTCUSDT pricePrecision

cos the QUARTER and PERPETUAL with the same "pair", but not the same "symbol"....

**Comment by saleh-mir** [comment]
It always uses PERPETUAL data as only they are supported by Jesse
