### ISSUE TITLE
download link on the website are broken

### ISSUE THREAD

**Issue by movy** [jesse-ai/jesse#376]
I've checked links for several releases and platforms, all of them generate 404, example:
https://jesse.trade/releases/download/447

![image](https://user-images.githubusercontent.com/4336560/195495489-a62bac46-964d-4720-8a92-0893fd6fd2af.png)

**Comment by saleh-mir** [comment]
Just checked. You're right. Thank you for reporting it. 

However, they're not needed. The new recommended method of installation is via the `jesse install-live` command (docker installations are even more automated). 

Please read:
https://docs.jesse.trade/docs/livetrade.html#installation
