### ISSUE TITLE
After a position opened using different time window in order to check situation

### ISSUE THREAD

**Issue by aykutdemirel** [jesse-ai/jesse#380]
The problem is that your strategy is working for a specific time frame or time window which is fine, every candle arrive according to selected time window.

But after making a decision where ever you want to go (long/short), maybe it would be very helpful checking your situation more frequently than your selected time frame.

Example;

You made your decision using 12H time frame, but you want to check your order by 30 minutes time frame in order to check signals that will help you. You may want to close your position based on that signal.

I couldn´t fine this usage in backtest (documents) could it be a future or its already there?

Thank you very much.

**Comment by cryptocoinserver** [comment]
[https://jesse.trade/help/faq/can-i-trade-one-timeframe-but-run-update-position-in-another-timeframe](https://jesse.trade/help/faq/can-i-trade-one-timeframe-but-run-update-position-in-another-timeframe)

It's already possible. See above. In short: use the smaller timeframe and make sure the entry happens on the close of the bigger one.

**Comment by saleh-mir** [comment]
Please use Discord for support-related questions:
https://jesse.trade/discord

We use GitHub only for issues such as bugs.
