### ISSUE TITLE
Option Support

### ISSUE THREAD

**Issue by yashwardhan-gautam** [jesse-ai/jesse#412]
Hello guys.
I have some strategies that work in option crypto market, I want to backtest them, and use in live mode too.
Does jesse support crypto option simulation ?  How to get the data for crypto option for daily expiry (especially the instruments that have already expired).
In documentation it says live trade plugin exists for Binance future(not sure if option is also supported, i haven't tried the live plugin yet).
Currently, I'm trading on `https://www.binance.com/en/eoptions/{instrument}` using some scripts. 
I'm not 100% sure, if platform supports this. If it already supports that, please enlighten.

Thanks for making such awesome project!

**Comment by saleh-mir** [comment]
Hey man, a few years ago when I was using Jesse in the crypto hedge fund I worked for, I was working on adding support for options trading. However, I left it for the future and haven't had the opportunity to tackle it again. Currently, Jesse doesn't support options trading, and there is no specific release date for adding this feature.

It's good to have you here I hope the future trading part of Jesse helps you.

**Comment by yashwardhan-gautam** [comment]
No problem.
Thanks for the quick reply!
