### ISSUE TITLE
circular dependency with python 3.11

### ISSUE THREAD

**Issue by movy** [jesse-ai/jesse#416]
I have tried installing Jesse 0.44 on Ubuntu 22.04 with Python 3.11, and on two different machines I encountered the same error:

```py
ImportError: cannot import name 'notify' from partially initialized module 'jesse.services.notifier' (most likely due to a circular import) (/home/ubuntu/.local/lib/python3.11/site-packages/jesse/services/notifier.py)
```

There is in fact a circular import between `notifier.py` and `logger.py`, but somehow it wasn't an issue with prior python versions. As a temporary solution I removed `from jesse.services import logger` from `notifier.py` and commented out all logging within notifier class, but I guess there's a better way to resolve it.

**Comment by saleh-mir** [comment]
Hey, man. Thank you for reporting this. I just pushed the fix. Can you confirm if it worked?

**Comment by saleh-mir** [comment]
I think this is resolved. If it's not, please let me know so I can reopen it.
