### ISSUE TITLE
Bug - link not working 

### ISSUE THREAD

**Issue by kshitiz305** [jesse-ai/jesse#417]
**Describe the bug**
While reading the readme.md I got to know that the read me file has a link that is not working.

**Expected behavior**
The "Here" link is not working, It is giving a 404 error. 

**Screenshots**
![image](https://github.com/jesse-ai/jesse/assets/38988779/95ce1d4f-c14e-4b8c-97ea-dcaefd896c04)

**Additional context**

**Comment by kshitiz305** [comment]
Could you kindly provide me with a correct link so that it can be updated.

**Comment by saleh-mir** [comment]
Thank you for informing me about it. The new page is simply the front page of the documentation.
https://docs.jesse.trade

**Comment by kshitiz305** [comment]
Hey @saleh-mir I would like to know if we are still planning on further releases for Jesse and if there are further plans to add more introduce new features to it .

**Comment by saleh-mir** [comment]
Of course, there is. That's what I work on every day. It's just that some features take longer to ship, and some are about what happens behind the scenes of my website, which takes long but doesn't seem exciting. Here's the roadmap, but it doesn't have everything that I have in mind, just a few.
https://docs.jesse.trade/docs/roadmap#roadmap
