### ISSUE TITLE
Error "422 Unprocessable Entity" when using "+ Start in a new tab" button

### ISSUE THREAD

**Issue by NicoSan20** [jesse-ai/jesse#460]
Each time I use the button "+ Start in a new tab" I got "422 Unprocessable Entity" error popup and also into terminal log. This happend on all "+ Start in a new tab" (Backtest and Import Candles page)

![image](https://github.com/jesse-ai/jesse/assets/65957648/a2d4afc1-81e9-448f-b344-ff5d7872d10c)

Maybe I'm doing something wrong, but I don't think we can go wrong using this button.

My environnement is an Ubuntu Server 22.04 fresh installation with Jesse 0.48.6 installation from the following script (https://raw.githubusercontent.com/jesse-ai/stack-installer/master/ubuntu-22.04.sh)

Thank you in advance for your help. Best regards.

**Comment by saleh-mir** [comment]
Hey man, I just tested this with the imported candles and it works fine for me. to debug this, I'm going to need to see the logs from the network section of your browser to get more details about it. 

However, I'm working on the new dashboard to release it as soon as possible, and a lot has been rewritten in it. Basically, the entire front end has been rewritten from scratch, so please wait until that is out.

**Comment by NicoSan20** [comment]
@saleh-mir Just in case of, here is the result of the request in network section of my browser ;)

'''
{
    "detail": [
        {
            "type": "string_type",
            "loc": [
                "body",
                "id"
            ],
            "msg": "Input should be a valid string",
            "input": 5,
            "url": "https://errors.pydantic.dev/2.7/v/string_type"
        }
    ]
}
'''

**Comment by saleh-mir** [comment]
Is this for import candles or backtest?

**Comment by NicoSan20** [comment]
@saleh-mir This happened on both (import candles and backtest)
