### ISSUE TITLE
Take profit & stop loss strategies into the route

### ISSUE THREAD

**Issue by NicoSan20** [jesse-ai/jesse#463]
This is my opinion, but an interesting feature would be to set up an take profit and stop loss strategies in the route. For example, in the route, it would be possible to select different take profit and stop loss strategies from a list (e.g. % or x(ATR) or x(swing), etc.).

This would make it easy to test different take profit and stop loss methods on a trading strategy.

I've seen this in other bot and I think it would be interesting to have it in Jesse too :)

**Comment by saleh-mir** [comment]
Hi, thank you for your suggestion. If you check out some of my videos and see how I set the stop loss dynamically, you'll see that it actually doesn't make sense to set a specific percentage number for the stop loss.

I know what you're referring to, but I find that very unprofessional and a bit too simplistic.
