### ISSUE TITLE
Since Jesse bot is a paid-version, wanted to understand more features regarding the bot such as follows: a) Does Jesse bot support User's inputs as the 1st measure and thereafter followed by customising the strategy? b) If we create our own bot from the scratch, does it return its own API?

### ISSUE THREAD

**Issue by shubhamraut41** [jesse-ai/jesse#471]

**Comment by saleh-mir** [comment]
Please don't open issues for such questions. 

Also, it seems like you have no idea what Jesse is. Please watch some of my videos or read the documentation. 

Additionally, only some of the features are paid. You can get started for free. Start doing that and test things for free.

**Comment by shubhamraut41** [comment]
Thanks for your assist.
