### ISSUE TITLE
Open multiple positions

### ISSUE THREAD

**Issue by Nemmo** [jesse-ai/jesse#8]
Hi!

How can I tell it to open another positions of the same strategy if the previous has been still holding?
For example I want to have 10 opened positions at the same time.

**Comment by Gabri** [comment]
https://docs.jesse-ai.com/docs/strategies/entering-and-exiting.html#update-position @Nemmo

**Comment by saleh-mir** [comment]
If you mean how to open multiple positions per the same exchange-symbol pair, you can't. 

However, if you mean how to open multiple positions with multiple pairs like for example:
`binance-BTCUSD` and `binance-ETHUSD` then you need to set one route per each:
https://docs.jesse-ai.com/docs/routes.html#routing

**Comment by Nemmo** [comment]
> If you mean how to open multiple positions per the same exchange-symbol pair, you can't.

Yeap, exactly.  But why not? Will you ship that feature later?

**Comment by saleh-mir** [comment]
My number one goal for Jesse is to make the strategy development easy by making it simple. 

It's just hard for me to think in matter of more than one position at the same time; as it is the case on future markets. For example you can't actually open a long and a short position at the same time on them. 

I wan't that `should_long`  and `should_short` to be for entering trades ONLY. As if once the position is opened, `should_long`  and `should_short` won't even get called. This has made it so much simpler in my own experience in developing strategies with Jesse. 

I'll publish a step by step tutorial article soon as an example of developing a strategy with Jesse.
