### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by yangboz** [jesse-ai/jesse#95]
system info:
```
macosx 11.0.1 

Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 17:50:39) 
[GCC Clang 10.0.0 ] on darwin


```

docker info:
```
Docker version 19.03.13, build 4484c46d9d
```
error info: 
```
14cb0f48885a: Pull complete 
Digest: sha256:8e329b49694c3feb55053d78304b100826d59beedf6447d746fefb32f682baea
Status: Downloaded newer image for salehmir/jesse:python38
docker: Error response from daemon: error while creating mount source path '/Users/saleh/Codes/tests/docker/home': mkdir /Users/saleh: operation not permitted.

```

**Comment by saleh-mir** [comment]
Hey, sorry for late reply. Are you using the official image? I need to update that one. 

Can you also try it with this one that uses docker compose:
https://github.com/jesse-ai/jesse-stack-docker

**Comment by mads03dk** [comment]
Hey. I made a [PR with a Dockerfile](https://github.com/jesse-ai/jesse/pull/103), so it can be Integrated with travis.ci. Works flawlessly for me

**Comment by saleh-mir** [comment]
I'm also dropping support for Python 3.6 as Pandas did recently
